"""Compact, training-grounded meanings for the exact BANKING77 labels."""

from __future__ import annotations


INTENT_GUIDE: dict[str, str] = {
    "Refund_not_showing_up": "A merchant refund is already due or issued but is not visible in the account or statement.",
    "activate_my_card": "How to activate a newly received physical card.",
    "age_limit": "Minimum or maximum age for opening or using the account.",
    "apple_pay_or_google_pay": "Using the service or card with Apple Pay or Google Pay.",
    "atm_support": "Which ATMs, ATM networks, or locations can be used for cash withdrawal.",
    "automatic_top_up": "Setting up, changing, or understanding automatic card top-ups.",
    "balance_not_updated_after_bank_transfer": "An inbound bank transfer was already made to the user's own account, but the balance has not updated.",
    "balance_not_updated_after_cheque_or_cash_deposit": "Cash or cheque was already deposited, but the account balance has not updated.",
    "beneficiary_not_allowed": "A recipient or beneficiary cannot be added, selected, or used for a transfer, including blocked crypto beneficiaries.",
    "cancel_transfer": "Cancelling or reversing a money transfer after it was initiated.",
    "card_about_to_expire": "A physical card is expiring soon and the user needs renewal or replacement information.",
    "card_acceptance": "Where, with which merchants, or in which situations the issued card can be used.",
    "card_arrival": "Tracking or locating a physical card that has already been ordered or dispatched, including a late card.",
    "card_delivery_estimate": "Normal or prospective physical-card delivery time, speed, date, or delivery options.",
    "card_linking": "Linking an existing, new, previous, or replacement card to the app or account.",
    "card_not_working": "The physical card broadly does not function, without a more specific ATM, merchant-payment, contactless, or virtual-card scenario.",
    "card_payment_fee_charged": "A fee was charged specifically for making a merchant purchase with the card.",
    "card_payment_not_recognised": "A merchant card purchase or card payment is not recognised by the user.",
    "card_payment_wrong_exchange_rate": "A merchant card purchase used an incorrect currency exchange rate.",
    "card_swallowed": "An ATM retained or swallowed the physical card.",
    "cash_withdrawal_charge": "A fee was charged for withdrawing cash from an ATM.",
    "cash_withdrawal_not_recognised": "An ATM cash withdrawal is not recognised by the user.",
    "change_pin": "Changing the physical card PIN.",
    "compromised_card": "The physical card may be compromised or its details exposed, without one specific disputed payment or withdrawal.",
    "contactless_not_working": "Contactless or tap-to-pay on the physical card is not working.",
    "country_support": "Countries where the banking service is available to residents or customers.",
    "declined_card_payment": "A merchant card payment was explicitly declined or rejected.",
    "declined_cash_withdrawal": "An ATM explicitly refused or declined a cash withdrawal.",
    "declined_transfer": "A money transfer has an explicit declined or rejected status.",
    "direct_debit_payment_not_recognised": "A direct debit, mandate-based debit, or explicitly named direct-debit payment is not recognised.",
    "disposable_card_limits": "Usage, transaction, merchant, or frequency limits for disposable virtual cards.",
    "edit_personal_details": "Changing personal data such as name, address, phone number, or other profile details.",
    "exchange_charge": "Fees or charges for converting one currency into another.",
    "exchange_rate": "The current, quoted, or generally applicable currency conversion rate.",
    "exchange_via_app": "How or whether to convert one named currency to another inside the app.",
    "extra_charge_on_statement": "An unexplained small extra card verification charge on a statement, commonly about 1 GBP, EUR, or USD.",
    "failed_transfer": "A money transfer failed or did not go through because of a processing or technical failure, rather than an explicit pending status.",
    "fiat_currency_support": "Which fiat currencies the account can hold, exchange, or maintain as balances.",
    "get_disposable_virtual_card": "How to obtain or find a disposable virtual card.",
    "get_physical_card": "How or when to find or receive the PIN for a new physical card, including whether the PIN arrives separately.",
    "getting_spare_card": "Obtaining an additional, extra, or spare physical card and any related price.",
    "getting_virtual_card": "How to obtain, find, or access a normal virtual card.",
    "lost_or_stolen_card": "The physical card is lost or stolen and must be frozen, replaced, or reported.",
    "lost_or_stolen_phone": "The phone containing the banking app is lost or stolen.",
    "order_physical_card": "How to order or obtain the physical card, including its price or order requirements.",
    "passcode_forgotten": "The user forgot the app or account passcode; this is not the physical card PIN.",
    "pending_card_payment": "A merchant card payment is shown as pending or has not yet completed.",
    "pending_cash_withdrawal": "An ATM cash withdrawal is shown as pending, often even though cash was not received.",
    "pending_top_up": "A card top-up is shown as pending or still processing.",
    "pending_transfer": "A money transfer is explicitly shown as pending or still processing.",
    "pin_blocked": "The physical card PIN is blocked, usually after too many incorrect attempts.",
    "receiving_money": "How to receive salary, employer payments, or money from another person, including receiving in another currency.",
    "request_refund": "How to request a refund or cancel a merchant card purchase and obtain the money back.",
    "reverted_card_payment?": "A card payment was reversed or reverted and the money was automatically returned.",
    "supported_cards_and_currencies": "Which external cards and currencies are accepted specifically for funding the account by card top-up.",
    "terminate_account": "Closing, deleting, or terminating the account.",
    "top_up_by_bank_transfer_charge": "Fees for adding money to the account by bank transfer.",
    "top_up_by_card_charge": "Fees for adding money to the account using an external payment card.",
    "top_up_by_cash_or_cheque": "Adding money using cash or cheque, or asking whether that is supported.",
    "top_up_failed": "A card top-up failed or could not be processed.",
    "top_up_limits": "Minimum, maximum, daily, or other amount limits for top-ups.",
    "top_up_reverted": "A completed-looking card top-up was reversed, cancelled, or returned to the funding card.",
    "topping_up_by_card": "The procedure for adding money with an external debit or credit card.",
    "transaction_charged_twice": "The same merchant card transaction or purchase was charged twice.",
    "transfer_fee_charged": "A fee was deducted from or charged for a money transfer.",
    "transfer_into_account": "How to fund the user's own account by making a bank transfer into it.",
    "transfer_not_received_by_recipient": "An outbound transfer was already sent, but the intended recipient has not received it.",
    "transfer_timing": "A general or prospective question about how long a bank transfer will take, without a specific completed transfer already missing.",
    "unable_to_verify_identity": "Identity verification was attempted but fails or cannot be completed.",
    "verify_my_identity": "How to complete identity verification or which documents and steps are required.",
    "verify_source_of_funds": "How to prove or verify where deposited money or funds came from.",
    "verify_top_up": "Verification or authentication of a card top-up, including 3-D Secure or verification codes.",
    "virtual_card_not_working": "A normal or disposable virtual card fails when used.",
    "visa_or_mastercard": "Whether the issued physical card is Visa or Mastercard, or whether one can be chosen.",
    "why_verify_identity": "Why identity verification is required or what purpose it serves.",
    "wrong_amount_of_cash_received": "An ATM dispensed a different amount of cash from the amount requested or debited.",
    "wrong_exchange_rate_for_cash_withdrawal": "An ATM cash withdrawal used an incorrect currency exchange rate.",
}
